import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { buildMetadata } from "@/lib/seo";

export const metadata: Metadata = buildMetadata({
  title: "Methodology — UK Take Home Calculator",
  description:
    "How UK Take Home Calculator computes tax, NI, student loans, pensions and dividends. Sources, assumptions and limitations.",
  path: "/methodology",
});

export default function MethodologyPage() {
  return (
    <article className="prose mx-auto max-w-3xl px-4 py-10 dark:prose-invert">
      <Breadcrumbs items={[{ name: "Home", path: "/" }, { name: "Methodology", path: "/methodology" }]} />
      <h1 className="text-3xl font-bold">Methodology</h1>
      <p>
        UK Take Home Calculator uses a deterministic tax engine keyed on the
        HMRC 2025/26 tax year. All figures on the site are produced by that
        engine — no numbers are hand‑written or generated by AI.
      </p>
      <h2 className="mt-8 text-2xl font-semibold">What we calculate</h2>
      <ul className="list-disc pl-6">
        <li>Income Tax across UK (rUK) and Scottish bands, respecting the Personal Allowance taper above £100,000.</li>
        <li>Class 1 employee National Insurance (8% between the Primary Threshold and Upper Earnings Limit, 2% above).</li>
        <li>Student loan Plan 1 / 2 / 4 / 5 and Postgraduate loan (correctly stacked, lowest undergraduate threshold applies + PG additive).</li>
        <li>Pension salary sacrifice and net pay contributions.</li>
        <li>Umbrella / Inside IR35 approximation (employer NI, apprenticeship levy, umbrella margin).</li>
        <li>Limited Company Outside IR35 approximation (director salary + dividends + corporation tax with marginal relief).</li>
        <li>Period conversions across annual, monthly, four‑weekly, fortnightly, weekly, daily, hourly.</li>
      </ul>
      <h2 className="mt-8 text-2xl font-semibold">Sources</h2>
      <ul className="list-disc pl-6">
        <li>HMRC — Income Tax rates & Personal Allowance (2025/26)</li>
        <li>HMRC — National Insurance rates and letters (Class 1 employee, 2025/26)</li>
        <li>Scottish Government — Scottish Income Tax bands 2025/26</li>
        <li>Student Loans Company — Plan thresholds & rates</li>
        <li>Companies House / HMRC — Corporation Tax marginal relief formula</li>
      </ul>
      <h2 className="mt-8 text-2xl font-semibold">Percentile methodology</h2>
      <p>
        The percentile tool uses indicative values derived from published HMRC
        Survey of Personal Incomes and ONS ASHE releases. Numbers should be
        treated as approximate and refreshed against the latest published
        release.
      </p>
      <h2 className="mt-8 text-2xl font-semibold">Limitations</h2>
      <ul className="list-disc pl-6">
        <li>The engine covers common PAYE and contractor scenarios but is not a substitute for professional tax advice.</li>
        <li>Umbrella and LtdCo scenarios use industry‑standard approximations; margins and structures vary.</li>
        <li>Regional variations (e.g. Welsh Rates of Income Tax) are treated as identical to rUK where they currently match; future divergence would require an update here.</li>
        <li>Non‑standard tax codes are approximated (BR, D0, D1, NT). K codes are not fully modelled.</li>
      </ul>
      <p className="mt-8 text-sm text-zinc-500">Nothing on this site is regulated financial advice.</p>
    </article>
  );
}
